//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthEntity
    {
        public AuthEntity()
        {
            this.TreeItems = new HashSet<TreeItem>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegisteredAtUtc { get; set; }
        public Nullable<System.DateTime> LastActiveAtUtc { get; set; }
        public string RegisteredFromIpAddress { get; set; }
    
        public virtual ICollection<TreeItem> TreeItems { get; set; }
    }
}
