//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.Web.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganizerEntities : DbContext
    {
        public OrganizerEntities()
            : base("name=OrganizerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TreeItem> TreeItems { get; set; }
        public DbSet<TreeItemUrl> TreeItemUrls { get; set; }
        public DbSet<AuthEntity> AuthEntities { get; set; }
    }
}
