//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeItem
    {
        public TreeItem()
        {
            this.TreeItems1 = new HashSet<TreeItem>();
            this.TreeItems11 = new HashSet<TreeItem>();
            this.TreeItemUrls = new HashSet<TreeItemUrl>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedUtc { get; set; }
        public System.DateTime LastModifiedUtc { get; set; }
        public Nullable<bool> ShareRead { get; set; }
        public Nullable<System.DateTime> DueTimeUtc { get; set; }
        public Nullable<System.Guid> AuthEntityId { get; set; }
        public string ChildrenDisplayMode { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool IsCollapsed { get; set; }
        public Nullable<System.Guid> LastModifiedEntityId { get; set; }
        public Nullable<System.Guid> NextSiblingId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> ShareWrite { get; set; }
        public bool AutoLoadNestedChildrenIfNotRoot { get; set; }
    
        public virtual ICollection<TreeItem> TreeItems1 { get; set; }
        public virtual TreeItem TreeItem1 { get; set; }
        public virtual ICollection<TreeItem> TreeItems11 { get; set; }
        public virtual TreeItem TreeItem2 { get; set; }
        public virtual ICollection<TreeItemUrl> TreeItemUrls { get; set; }
        public virtual AuthEntity AuthEntity { get; set; }
    }
}
