//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeItemUrl
    {
        public System.Guid TreeItemId { get; set; }
        public string Url { get; set; }
    
        public virtual TreeItem TreeItem { get; set; }
    }
}
